sudo: required

services:
  - docker

before_install:
- docker pull homeassistant/home-assistant

script:
- cp secrets.yaml.example secrets.yaml
- docker run -v .:/config homeassistant/home-assistant python -m homeassistant --config /config --script config_check
