language: c # not actually c, but this has less dependencies than default ruby language

sudo: required

services:
  - docker

before_install:
  - docker pull homeassistant/home-assistant
  - docker pull boiyaa/yamllint

script:
  - "cp secrets.yaml.example secrets.yaml"
  - "script/test"
