homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret homeassistant_elevation
  # metric for Metric, imperial for Imperial
  unit_system: !secret homeassistant_unit_system
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret homeassistant_time_zone
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google

group: !include groups.yaml
automation: !include_dir_merge_list automations
panel_iframe: !include panel_iframe.yaml

ecobee: !include ecobee.yaml
input_select: !include input_selects.yaml
light hue: !include hue.yaml
media_player sonos: !include sonos.yaml
media_player kodi: !include kodi.yaml
mqtt: !include mqtt.yaml
nest: !include nest.yaml
notify slack: !include notify-slack.yaml
scene directory: !include_dir_list scenes
scene: !include scenes.yaml
script: !include_dir_named scripts
sensor bedtime: !include bedtime-sensor.yaml
sensor speedtest: !include speedtest.yaml
sleepiq: !include sleepiq.yaml
sun:
switch harmony hub: !include harmony-switches.yaml
switch house modes: !include house-modes.yaml
switch fireplace: !include fireplace-switch.yaml
vera: !include vera.yaml
switch rachio: !include rachio.yaml

apcupsd:
binary_sensor apcupsd-binary-sensor:
  - platform: apcupsd
sensor apcups-sensord:
  - platform: apcupsd
    resources:
      - bcharge
      - linev
      - loadpct
      - nominv
      - numxfers
      - status
      - timeleft
      - tonbatt

cloud:
  mode: !secret cloud_mode
  cognito_client_id: !secret cloud_cognito_client_id
  user_pool_id: !secret cloud_user_pool_id
  region: !secret cloud_region
  relayer: !secret cloud_relayer
  alexa: !include alexa.yaml
