homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: !secret homeassistant_unit_system
  time_zone: !secret homeassistant_time_zone
  customize: !include customize.yaml
  packages: !include_dir_named packages

cloud:
  alexa: !include alexa.yaml
config:
discovery:
frontend:
  javascript_version: latest
history:
http:
logbook:
recorder:
  purge_keep_days: 10
updater:
  include_used_components: true

group: !include groups.yaml
panel_iframe: !include panel_iframe.yaml

apcupsd:
ecobee: !include ecobee.yaml
light:
  - !include hue.yaml
media_player:
- !include sonos.yaml
- !include kodi.yaml
mqtt: !include mqtt.yaml
nest: !include nest.yaml
notify:
-  !include notify-slack.yaml
prometheus:
scene directory: !include_dir_list scenes
scene: !include scenes.yaml
script: !include scripts.yaml
sleepiq: !include sleepiq.yaml
sensor:
  - platform: yr
sun:
switch:
  - !include broadlink.yaml
  - !include rachio.yaml
vera: !include vera.yaml
