homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: !secret homeassistant_unit_system
  time_zone: !secret homeassistant_time_zone

  # packages is where the real magic lives
  customize: !include customize.yaml
  packages: !include_dir_named packages

# core components
frontend:
  javascript_version: latest
config:
discovery:
history:
http:
logbook:
recorder:
  purge_keep_days: 10
updater:
  include_used_components: true
sun:

# miscellany automations, see packages above for grouped functionality
group: !include groups.yaml
panel_iframe: !include panel_iframe.yaml
scene: !include scenes.yaml
scene directory: !include_dir_list scenes
script: !include scripts.yaml

# services & hardware components
apcupsd:
cloud:
  alexa: !include alexa.yaml
ecobee: !include ecobee.yaml
light:
  - !include hue.yaml
media_player:
- !include kodi.yaml
- !include sonos.yaml
mqtt: !include mqtt.yaml
nest: !include nest.yaml
notify:
-  !include notify-slack.yaml
prometheus:
sleepiq: !include sleepiq.yaml
sensor:
  - !include darksky.yaml
switch:
  - !include broadlink.yaml
#  - !include rachio.yaml
vera: !include vera.yaml
