homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 32.036018
  longitude: -81.098116
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:

homekit_controller:
ios:

# Sensors
sensor:
  # Weather prediction
  - platform: yr

# Thermostat
ecobee:
  api_key: !secret ecobee_api_key

# Text to speech
tts:
  - platform: google_translate

cloud:
  alexa:
    filter:
      include_domains:
      # start with include_domain defaults, less ones we exclude
      - alert
      - cover
      - fan
      - input_boolean
      - lock
      - scene
      - switch
      # technically don't need to exclude them if we only include some domains
      # but this lets us list them out and comment individually on why
      exclude_domains:
        # we have lots of lights, some with just numbers ie Kitchen 1 through Kitchen 8
        # so we'll exclude and list out specifically
        - light
        # We're using the Sonos Skill, which finds all the media players already
        # so hass would be duplicating them.
        # we'll specifically include media_players we want voice control for
        - media_player
      include_entities:
      # hue light groups
      - light.bedroom
      - light.break_room
      - light.exterior
      - light.kitchen
      - light.media_room
      - light.living_room
      - light.break_room
      - light.network_closet
      - light.tracy_desk
      - light.office
      - light.nursery

      # individual hue lights
      - light.tracy_night_stand
      - light.josh_night_stand
      - light.makeup_table
      - light.lady_cave_reading_lamp
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

input_boolean:
  josh_working:
    name: Josh working
    initial: off
    icon: mdi:office-building