homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: !secret homeassistant_unit_system
  time_zone: !secret homeassistant_time_zone

  customize: !include customize.yaml
  # packages is where the real magic lives
  packages: !include_dir_named packages

  auth_providers:
    - type: homeassistant
    - type: legacy_api_password

# core components
auth:
config:
discovery:
frontend:
  javascript_version: latest
  extra_html_url: []
history:
http:
  api_password: !secret http_api_password
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1
logbook:
logger:
  default: info
  logs:
    # ignore auth warnings like:
    # - Please use access_token instead api_password (https://github.com/home-assistant/home-assistant/issues/15423)
    homeassistant.components.http.auth: error
    homeassistant.components.http: error

    # ignore sonos warnings, like:
    # - Could not handle track info: ""
    # - Update for media_player.kitchen fails (https://github.com/technicalpickles/picklehome-homeassistant-config/issues/35)
    homeassistant.components.media_player.sonos: error
    soco.core: error

    # ignore warnings like:
    # - Found malformed XML at http://123.123.123.123:9080: status=ok
    netdisco.ssdp: error
    ssdp: error
recorder:
  purge_keep_days: 10
updater:
  include_used_components: true

# miscellany automations, see packages above for grouped functionality
panel_iframe: !include panel_iframe.yaml
scene: !include scenes.yaml
scene directory: !include_dir_list scenes
script: !include scripts.yaml

# services & hardware components
apcupsd:
binary_sensor:
- platform: rachio
ecobee: !include ecobee.yaml
hue: !include hue.yaml
influxdb: !include influxdb.yaml
media_player:
- !include kodi.yaml
mqtt: !include mqtt.yaml
nest: !include nest.yaml
notify:
-  !include notify-slack.yaml
prometheus:
rachio: !include rachio.yaml
sleepiq: !include sleepiq.yaml
sensor:
  - !include darksky.yaml
switch:
  - !include broadlink.yaml
  - platform: rachio
vera: !include vera.yaml
sun:
