title: Picklehome
views:
  - title: Home
    icon: mdi:heart
    cards:
      - type: picture-glance
        title: Living Room
        image: /local/living_room.jpeg
        navigation_path: /lovelace/living-room
        entities:
          - light.living_room
          - lock.front_door_12

      - type: picture-glance
        title: Kitchen
        image: /local/kitchen.jpeg
        navigation_path: /lovelace/kitchen
        entities:
          - light.kitchen
          - lock.kitchen_front_door_11
          - lock.kitchen_side_door_13

      - type: picture-glance
        title: Cottage
        image: /local/cottage.jpeg
        navigation_path: /lovelace/cottage
        entities:
          - climate.cottage
          - lock.cottage_back_door_15
          - lock.cottage_front_door_16

      - type: picture-glance
        title: Exterior
        image: /local/exterior.jpeg
        navigation_path: /lovelace/exterior
        entities:
          - light.exterior

      - type: entities
        title: House Modes
        entities:
          - switch.bath_mode
          - switch.porch_mode
          - script.good_night
          - script.good_morning
          - script.bed_time

      - type: entities
        title: Sun
        show_header_toggle: false
        entities:
          - script.sunrise
          - script.sunset

      - type: entities
        show_header_toggle: false
        entities:
          - climate.home
          - input_boolean.guest_mode
          - switch.fireplace
          - sensor.subjective_exterior_temperature

  - title: Living Room
    id: living-room
    cards:
     - type: glance
       entities:
         - switch.fireplace
         - switch.aquarium
         - switch.beach
         - switch.ducks
         - switch.turtles

  - title: Kitchen
    id: kitchen
    cards:
      - type: entities
        title: Locks
        entities:
          - lock.kitchen_front_door_11
          - lock.kitchen_side_door_13
       
      - type: entities
        title: Lights
        entities:
          - light.kitchen_front_1
          - light.kitchen_front_2
          - light.kitchen_front_3
          - light.kitchen_front_4
          - light.kitchen_back_1
          - light.kitchen_back_2
          - light.kitchen_back_3
          - light.kitchen_back_4
          - light.kitchen_back_5
          - light.kitchen_back_6
          - light.kitchen_back_7
          - light.kitchen_back_8

      - type: media-control
        entity: media_player.kitchen

      - type: entities
        title: Switches
        entities:
          - switch.kitchen_smart_plug_18

  - title: Cottage
    id: cottage
    cards:
      - type: entities
        name: Locks
        entities:
          - lock.cottage_back_door_15
          - lock.cottage_front_door_16
      - type: entities
        entities:
          - climate.cottage
          - group.cottage_outside_lights
          - switch.cottage_smart_plug_20
          - group.cottage_locks
          - input_boolean.guest_mode

  - title: Exterior
    id: exterior
    icon: mdi:weather-sunny
    cards:
      - type: weather-forecast
        entity: weather.home

      - type: entities
        title: Kitchen Door Lights
        entities:
          - light.kitchen_door_1
          - light.kitchen_door_2

      - type: entities
        title: Front Door Lights
        entities:
          - light.front_door_1
          - light.front_door_2

      - type: entities
        title: Front Side Door Lights
        entities:
          - light.kitchen_side_door_light
