title: Picklehome
views:
  - title: Home
    path: home
    icon: mdi:heart
    cards:
      - type: picture-glance
        title: Living Room
        image: /local/private/IMG_1492.jpg
        #image: /local/living_room.jpeg
        tap_action:
          action: navigate
          navigation_path: /lovelace/living-room
        entities:
          - light.living_room
          - lock.front_door_12

      - type: picture-glance
        title: Kitchen
        image: /local/private/IMG_1490.jpg
        #image: /local/kitchen.jpeg
        tap_action:
          action: navigate
          navigation_path: /lovelace/kitchen
        entities:
          - light.kitchen
          - lock.kitchen_front_door_11
          - lock.kitchen_side_door_13

      - type: picture-glance
        title: Nursery
        image: /local/private/IMG_1493.jpg
        tap_action:
          action: navigate
          navigation_path: /lovelace/nursery
        entities:
          - light.nursery

      - type: picture-glance
        title: Media Room
        image: /local/private/IMG_1494.jpg
        tap_action:
          action: navigate
          navigation_path: /lovelace/media-room
        entities:
          - light.media_room

      - type: picture-glance
        title: Bedroom
        image: /local/private/IMG_1495.jpg
        tap_action:
          action: navigate
          navigation_path: /lovelace/bedroom
        entities:
          - light.bedroom

      - type: picture-glance
        title: Sunroom
        image: /local/sunroom.jpeg
        tap_action:
          action: navigate
          navigation_path: /lovelace/sunroom
        entities:
          - lock.sun_room_door_14

      - type: picture-glance
        title: Cottage
        image: /local/cottage.jpeg
        tap_action:
          action: navigate
          navigation_path: /lovelace/cottage
        entities:
          - climate.cottage
          - lock.cottage_back_door_15
          - lock.cottage_front_door_16

      - type: picture-glance
        title: Exterior
        image: /local/exterior.jpeg
        tap_action:
          action: navigate
          navigation_path: /lovelace/exterior
        entities:
          - light.exterior
      - type: glance
        entities:
          - lock.front_door_12
          - lock.kitchen_front_door_11
          - lock.kitchen_side_door_13
          - lock.sun_room_door_14

  - title: Automation
    icon: mdi:wrench
    id: automation
    cards:
      - type: entities
        title: House Modes
        show_header_toggle: false
        entities:
          - input_select.house_mode
          - switch.bath_mode
          - switch.porch_mode
          - script.good_night
          - script.good_morning
          - script.bed_time

      - type: entities
        title: Sun
        show_header_toggle: false
        entities:
          - automation.sunrise
          - automation.sunset

      - title: Home Climate
        type: entities
        show_header_toggle: false
        entities:
          - climate.home
          - sensor.subjective_exterior_temperature
          - automation.southern_comfort_applied_on_subjective_temperature_change
          - automation.southern_comfort_applied_periodically
          - script.apply_southern_comfort
      - title: Cottage Climate
        type: entities
        show_header_toggle: false
        entities:
          - climate.cottage
          - input_boolean.guest_mode
          - automation.guest_mode_applied_periodically
      - title: Fireplace
        type: entities
        show_header_toggle: false
        entities:
          - switch.fireplace
          - switch.aquarium
          - switch.beach
          - switch.ducks
          - switch.turtles
          - media_player.fireplace
          - input_select.fireplace_tv_source_selector
          - media_player.fireplace_kodi
      - title: Attic Fan
        type: entities
        show_header_toggle: false
        entities:
          - automation.attic_fan_automatic_off_with_lights
          - switch.attic_fan

  - title: Interior Temperature
    id: interior-temperature
    icon: mdi:thermostat
    badges:
      - climate.home
      - climate.cottage
    cards:
      - type: glance
        entities:
          - sensor.bedroom_temperature
          - sensor.media_room_temperature
          - sensor.home_temperature
          - sensor.nursery_temperature
          - sensor.josh_office_temperature
          - sensor.tracy_office_temperature
      - type: weather-forecast
        entity: weather.home

  - title: Living Room
    path: living-room
    badges:
      - lock.front_door_12
      - switch.christmas_tree
      - light.living_room

    cards:
     - type: entities
       entities:
         - switch.fireplace
         - switch.aquarium
         - switch.beach
         - switch.ducks
         - switch.turtles
     - type: entities
       title: Living Room Lights
       entities:
         - light.fireplace_backlight
         - light.living_room_lamp
         - light.living_room_sofa_strip
         - light.living_room_sofa_strip_2
         - light.living_room_rear_overhead_1
         - light.living_room_rear_overhead_2
         - switch.mantle_tree
     - type: media-control
       entity: media_player.living_room
     - type: media-control
       entity: media_player.fireplace_kodi

  - title: Media Room
    path: media-room
    badges:
      - binary_sensor.media_room_occupancy
      - sensor.media_room_temperature
    cards:
      - type: entities
        name: Lights
        entities:
          - light.media_room_front_left
          - light.media_room_front_right
          - light.media_stand_lightstrip
      - type: entities
        show_header_toggle: false
        name: TV
        entities:
          - switch.directv
          - switch.apple_tv
          - switch.smart_tv
          - switch.nintendo_switch
      - type: media-control
        entity: media_player.media_room
      - type: media-control
        entity: media_player.lvgrm
      - type: media-control
        entity: media_player.media_room_appletv

  - title: Bedroom
    path: bedroom
    badges:
      - binary_sensor.bedroom_occupancy
      - sensor.bedroom_temperature
    cards:
      - type: entities
        entities:
          - binary_sensor.sleepnumber_ile_josh_is_in_bed
          - sensor.sleepnumber_ile_josh_sleepnumber
          - binary_sensor.sleepnumber_ile_tracy_is_in_bed
          - sensor.sleepnumber_ile_tracy_sleepnumber
          - sensor.everyone_in_bed
      - type: entities
        show_header_toggle: false
        entities:
          - light.josh_night_stand
          - light.tracy_night_stand
          - light.makeup_table
      - type: media-control
        entity: media_player.bedroom

  - title: Sunroom
    path: sunroom
    badges:
      - lock.sun_room_door_14

  - title: Nursery
    path: nursery
    badges:
     - sensor.nursery_temperature
     - binary_sensor.nursery_occupancy
     - binary_sensor.nursery_door_23
    cards:
     - type: glance
       entities:
         - switch.nursery_night_light_22
         - light.nursery
         - camera.kids_room
     - type: media-control
       entity: media_player.nursery
     - type: picture-entity
       entity: camera.kids_room
       camera_image: camera.kids_room

  - title: Kitchen
    path: kitchen
    badges:
      - lock.kitchen_front_door_11
      - lock.kitchen_side_door_13
      - group.kitchen_lights
      - switch.kitchen_smart_plug_18

    cards:
      - type: entities
        title: Lights
        entities:
          - light.kitchen_front_1
          - light.kitchen_front_2
          - light.kitchen_front_3
          - light.kitchen_front_4
          - light.kitchen_back_1
          - light.kitchen_back_2
          - light.kitchen_back_3
          - light.kitchen_back_4
          - light.kitchen_back_5
          - light.kitchen_back_6
          - light.kitchen_back_7
          - light.kitchen_back_8

      - type: media-control
        entity: media_player.kitchen

      - type: entities
        title: Switches
        entities:
          - switch.kitchen_smart_plug_18

  - title: Attic
    path: attic
    badges:
      - binary_sensor.josh_office_occupancy
      - sensor.josh_office_temperature
      - binary_sensor.tracy_office_occupancy
      - sensor.tracy_office_temperature
      - switch.conference_call_mode
      - switch.attic_fan
    cards:
      - type: entities
        title: Josh's Desk Lamps
        entities:
          - light.josh_desk_left
          - light.josh_desk_right
      - type: entities
        title: Tracy's Desk Lamp
        entities:
          - light.tracy_desk_lamp_bulb_1
          - light.tracy_desk_lamp_bulb_2
          - light.tracy_desk_lamp_bulb_3
  - title: Laundry
    path: laundry
    badges:
      - switch.laundry_smart_plug_21

  - title: Cottage
    path: cottage
    badges:
      - switch.cottage_smart_plug_20
      - climate.cottage
      - input_boolean.guest_mode
    cards:
      - type: entities
        name: Locks
        entities:
          - lock.cottage_back_door_15
          - lock.cottage_front_door_16
      - type: entities
        entities:
          - light.cottage_courtyard
          - light.cottage_backyard

  - title: Exterior
    path: exterior
    icon: mdi:weather-sunny
    cards:
      - type: weather-forecast
        entity: weather.home

      - type: entities
        title: Kitchen Door Lights
        entities:
          - light.kitchen_door_1
          - light.kitchen_door_2

      - type: entities
        title: Front Door Lights
        entities:
          - light.front_door_1
          - light.front_door_2

      - type: entities
        title: Front Side Door Lights
        entities:
          - light.kitchen_side_door_light

      - type: entities
        title: Irrigation
        show_header_toggle: false
        entities:
          - switch.back_yard_left_2
          - switch.back_yard_right__2
