- alias: Everyone is in bed after sunset causes Bed Time
  trigger:
    platform: state
    entity_id: sensor.everyone_in_bed
    from: 'off'
    to: 'on'
  condition:
    condition: sun
    after: sunset
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.house_mode
        option: Bed Time

- alias: Lights out and in bed while in Bed Time causes Night Time
  trigger:
    platform: state
    entity_id: group.master_bedroom_lights
    to: 'off'
  condition:
    condition: template
    value_template: "{{ is_state('input_select.house_mode', 'Bed Time') }}"
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.house_mode
        option: Sleeping

- alias: Out of bed in the morning causes Awake
  trigger:
    platform: state
    entity_id: sensor.everyone_in_bed
    from: 'on'
    to: 'off'
    for:
      minutes: 20
  condition:
    condition: 'and'
    conditions:
      - condition: time
        after: '5:00:00'
        before: '14:00:00'
      - condition: state
        entity_id: input_select.house_mode
        state: 'Sleeping'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.house_mode
        option: Awake

- alias: Awake Triggered
  trigger:
    platform: state
    entity_id: input_select.house_mode
    to: Awake
  action:
  - service: notify.slack
    data:
      message: ":family: Good Morning :family:"

- alias: Bed Time Triggered
  trigger:
    platform: state
    entity_id: input_select.house_mode
    to: Bed Time
  action:
  - service: notify.slack
    data:
      message: ":family::bed:"

- alias: Sleeping Triggered
  trigger:
    platform: state
    entity_id: input_select.house_mode
    to: Sleeping
  action:
  - service: notify.slack
    data:
      message: ":family::zzz:"
  - service: scene.turn_on
    entity_id: scene.good_night
