automation:
  - alias: Attic Fan automatic off with lights
    trigger:
      - platform: state
        entity_id: light.josh_desk
        to: 'off'
        for:
          minutes: 10
    condition:
      condition: state
      entity_id: switch.attic_fan
      state: 'on'
    action:
      service: switch.turn_off
      entity_id: switch.attic_fan
