input_select:
  house_mode:
    name: House Mode
    initial: Awake
    options:
      - Awake
      - Bath Time
      - Bed Time
      - Sleeping

sensor:
- platform: template
  sensors:
    everyone_in_bed:
      friendly_name: "Everyone in Bed"
      value_template: >-
        {%- if is_state('binary_sensor.sleepnumber_ile_josh_is_in_bed', 'on') and is_state('binary_sensor.sleepnumber_ile_tracy_is_in_bed', 'on') %}
          on
        {%- else %}
          off
        {%- endif %}
    anyone_in_bed:
      friendly_name: "Anyone in Bed"
      value_template: >-
        {%- if is_state('binary_sensor.sleepnumber_ile_josh_is_in_bed', 'on') or is_state('binary_sensor.sleepnumber_ile_tracy_is_in_bed', 'on') %}
          on
        {%- else %}
          off
        {%- endif %}

automation:
  # automations to detect mode changes
  - alias: Out of bed,  nursery door open, or kitchen playing in the morning causes Awake
    trigger:
      - platform: state
        entity_id: sensor.everyone_in_bed
        from: 'on'
        to: 'off'
        for:
          minutes: 20
      - platform: state
        entity_id: binary_sensor.nursery_door_23
        to: 'on'
      - platform: state
        entity_id: media_player.kitchen
        to: 'playing'
    condition:
      condition: 'and'
      conditions:
        - condition: time
          after: '5:00:00'
          before: '14:00:00'
        - condition: state
          entity_id: input_select.house_mode
          state: 'Sleeping'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.house_mode
          option: Awake

  - alias: Everyone is in bed after Sunset changes to Bed Time
    trigger:
      platform: state
      entity_id: sensor.everyone_in_bed
      from: 'off'
      to: 'on'
    condition:
      condition: sun
      after: sunset
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.house_mode
          option: Bed Time
  
  - alias: Lights out and in bed while in Bed Time changes to Sleeping
    trigger:
      platform: state
      entity_id: group.bedroom_lights
      to: 'off'
    condition:
      condition: template
      value_template: "{{ is_state('input_select.house_mode', 'Bed Time') }}"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.house_mode
          option: Sleeping
  
  # what to do when the mode changes
  - alias: Awake Triggered
    trigger:
      platform: state
      entity_id: input_select.house_mode
      to: Awake
    action:
      service: script.good_morning
  
  - alias: Bed Time Triggered
    trigger:
      platform: state
      entity_id: input_select.house_mode
      to: Bed Time
    action:
      service: script.bed_time
  
  - alias: Sleeping Triggered
    trigger:
      platform: state
      entity_id: input_select.house_mode
      to: Sleeping
    action:
      - service: script.good_night
  
scene:
  - name: Alex Bedtime
    entities:
      switch.nursery_night_lights:
        state: on
  
  - name: Everything Off
    entities:
      group.media_room: off
      group.all_lights: off
      switch.christmas_lights: off
  
  - name: Goodbye
    entities:
      group.living_room_lights: on # so it seems like someone is inside
      switch.christmas_lights: off # christmas tree safety
  
script:
  goodbye:
    sequence:
      - service: script.media_room_off
      - service: script.attic_off
      - service: script.living_room_on

  good_night:
    sequence:
      # update to sleeping if it wasn't already
      - service: input_select.select_option
        data:
          entity_id: input_select.house_mode
          option: Sleeping
      - service: notify.slack
        data:
          message: ":family::zzz:"
      - service: script.living_room_off
      - service: script.media_room_off
      - service: script.attic_off
      - service: script.bedroom_off
      - service: script.kitchen_off
      - service: media_player.sonos_unjoin
  good_morning:
    sequence:
      # update to Awake if it wasn't already
      - service: input_select.select_option
        data:
          entity_id: input_select.house_mode
          option: Awake
      - service: notify.slack
        data:
          message: ":family: Good Morning :family:"
      - service: script.kitchen_on
      - service: script.living_room_on
      - service: media_player.sonos_unjoin

  bed_time:
    sequence:
      # update to Bed Time if it wasn't already
      - service: input_select.select_option
        data:
          entity_id: input_select.house_mode
          option: Bed Time
      - service: notify.slack
        data:
          message: ":family::bed:"
