
binary_sensor:
  platform: mqtt
  name: Josh Desk Cameras
  state_topic: "picklebook-pro/desk-cameras/state"
  payload_on: 'on'
  payload_off: 'off'

switch:
  platform: template
  switches:
    conference_call_mode:
      friendly_name: Conference Call Mode
      value_template: "{{ is_state_attr('light.josh_desk_right', 'brightness', 254) and is_state_attr('light.josh_desk_right', 'color_temp', 161) and is_state_attr('light.josh_desk_left', 'brightness', 254) and is_state_attr('light.josh_desk_left', 'color_temp', 161)}}"
      turn_on:
        service: scene.turn_on
        entity_id: scene.josh_desk_conference_call
      turn_off:
        service: scene.turn_on
        data_template:
          entity_id: >
            {% if is_state('sun.sun', 'below_horizon') %}
              scene.josh_desk_lamps_on
            {% else %}
              scene.josh_desk_lamps_off
            {% endif %}
scene:
  - name: Josh Desk Lamps Off
    entities:
      light.josh_desk: off
  - name: Josh Desk Conference Call
    entities:
      light.josh_desk:
        state: on
        brightness: 254
        color_temp: 161
  - name: Josh Desk Lights On
    entities:
      light.josh_desk:
        state: on
        brightness: 255
        profile: reading

automation:
  trigger:
    platform: state
    entity_id: binary_sensor.josh_desk_cameras
  action:
    service_template: switch.turn_{{ trigger.to_state.state }}
    entity_id: switch.conference_call_mode
