input_select:
  fireplace_tv_source_selector:
    name: Fireplace TV Sources Selector
    options:
      - Fire
      - Beach
      - Aquarium
    icon: mdi:video-input-hdmi

sensor:
  platform: template
  sensors:
    fireplace_videos_directory:
      value_template: !secret fireplace_videos_directory

script:
  fireplace_off:
    sequence:
      - service: media_player.turn_off
        entity_id: media_player.fireplace_kodi
      - service: light.turn_off
        entity_id: light.fireplace_backlight

  fireplace_on:
    sequence:
      - service: light.turn_on
        entity_id: light.fireplace_backlight
        data:
          rgb_color: [255,161,0]
          brightness: 144
      - service: script.fireplace_play
        data:
          file: The Best Fireplace Video (3 hours)-eyU3bRy2x44.mkv

  fireplace_play:
    sequence:
      - service: media_player.turn_on
        entity_id: media_player.fireplace_kodi
      - service: media_player.play_media
        entity_id: media_player.fireplace_kodi
        data_template:
          media_content_id: "{{states('sensor.fireplace_videos_directory')}}/{{file}}"
          media_content_type: "video"

  fireplace_stop:
    sequence:
    - service: media_player.media_stop
      data:
        entity_id: media_player.fireplace_kodi

automation:
  - alias: Select Fireplace Input
    trigger:
      - platform: state
        entity_id: input_select.fireplace_tv_source_selector
    action:
      - service: script.fireplace_play
        data_template:
          file: >
              {% if is_state("input_select.fireplace_tv_source_selector", "Fire") %}
                The Best Fireplace Video (3 hours)-eyU3bRy2x44.mkv
              {%-elif is_state("input_select.fireplace_tv_source_selector", "Beach") %}
                Nature Sounds Ocean Waves for relaxation, yoga, meditation, reading, sleep, study [ Sleep Music ]-MD0tXdSsnBA.mp4
              {%-elif is_state("input_select.fireplace_tv_source_selector", "Aquarium") %}
                HD Open-Aquarium - Inside a Tropical Lagoon-iu6xIdAdJwo.mp4
              {% endif %}

  - alias: Fireplace TV is idle for more than 30 minutes, turn it off.
    trigger:
     platform: state
     entity_id: media_player.fireplace_tv
     to: 'idle'
     for:
       minutes: 30
    action:
      - service: media_player.turn_off
        entity_id: media_player.fireplace_tv

media_player:
  - platform: universal
    name: fireplace
    friendly_name: Fireplace
    children:
      - media_player.fireplace_kodi
    state_template: >
      {% if is_state('switch.fireplace_tv_power', 'off') %}
      off
      {% else %}
      {{ states('media_player.fireplace_kodi') }}
      {% endif %}
    commands:
      turn_on:
        service: script.fireplace_on
      turn_off:
        service: script.fireplace_off
      select_source:
        service: input_select.select_option
        data_template:
          entity_id: input_select.fireplace_tv_source_selector
          option: '{{ source }}'

    attributes:
      state: media_player.fireplace_kodi
      source_list: input_select.fireplace_tv_source_selector|options

