switch:
  - platform: template
    switches:
      fireplace:
        friendly_name: Fireplace
        value_template: >
           {{ is_state("media_player.fireplace_kodi", "playing") }}
        turn_on:
          # use a script, because it runs asynchronously.
          # otherwise, when alexa-controlled, might timeout waiting for it to finish
          - service: script.fireplace_on
        turn_off:
          - service: script.fireplace_off

sensor:
  platform: template
  sensors:
    fireplace_videos_directory:
      value_template: !secret fireplace_videos_directory

script:
  fireplace_off:
    sequence:
      - service: media_player.turn_off
        entity_id: media_player.fireplace_kodi
      - service: light.turn_off
        entity_id: light.fireplace_backlight

  fireplace_on:
    sequence:
      - service: light.turn_on
        entity_id: light.fireplace_backlight
        data:
          rgb_color: [255,161,0]
          brightness: 144
      - service: script.fireplace_play
        data:
          file: The Best Fireplace Video (3 hours)-eyU3bRy2x44.mkv

  fireplace_play:
    sequence:
      - service: media_player.turn_on
        entity_id: media_player.fireplace_kodi
      - service: media_player.play_media
        entity_id: media_player.fireplace_kodi
        data_template:
          media_content_id: "{{states('sensor.fireplace_videos_directory')}}/{{file}}"
          media_content_type: "video"

  fireplace_stop:
    sequence:
    - service: media_player.media_stop
      data:
        entity_id: media_player.fireplace_kodi
