switch:
- platform: template
  switches:
    guest_mode:
      friendly_name: Guest Mode
      value_template: "{{ not (is_state_attr('climate.cottage', 'target_temp_low', 50) and is_state_attr('climate.cottage', 'target_temp_high', 78) and is_state_attr('climate.cottage', 'operation_mode', 'auto')) }}"
      turn_on:
        service: script.guest_mode_on
      turn_off:
        service: script.guest_mode_off

script:
  guest_mode_off:
    sequence:
      - service: climate.set_temperature
        entity_id: climate.cottage
        data:
          operation_mode: auto
          target_temp_low: 50
          target_temp_high: 78

  guest_mode_on:
    sequence:
      - service: climate.ecobee_resume_program
        entity_id: climate.cottage
