input_boolean:
  guest_mode:
    name: Guest Mode

automation:
  - alias: Guest Mode toggle
    trigger:
      platform: state
      entity_id: input_boolean.guest_mode
    action:
      service: script.apply_guest_mode

  - alias: Guest Mode applied periodically
    trigger:
      platform: time
      hours: '/2'
      minutes: 00
      seconds: 00
    action:
      - service: script.apply_guest_mode

script:
  apply_guest_mode:
    sequence:
      - service_template: "script.guest_mode_{{states('input_boolean.guest_mode')}}"
      #- service: notify.slack
      #  data_template:
      #    message: "Guest Mode {{states('input_boolean.guest_mode')}}"
  guest_mode_off:
    sequence:
      - service: climate.set_operation_mode
        entity_id: climate.cottage
        data:
          operation_mode: 'auto'
      - service: climate.set_temperature
        entity_id: climate.cottage
        data:
          operation_mode: auto
          target_temp_low: 50
          target_temp_high: 78

  guest_mode_on:
    sequence:
      - service: climate.set_operation_mode
        entity_id: climate.cottage
        data:
          operation_mode: 'auto'
      - service: climate.ecobee_resume_program
        entity_id: climate.cottage
