################################################################################
# Southern Comfort
# keeping things comfortable despite the day star's best efforts, and the
# apparent lack of smart thermostat developers living in the southeastern US
#
# Uses ecobee specific services (climate.ecobee_resume_program)
################################################################################

sensor:
  - platform: template
    sensors:
      subjective_exterior_temperature:
        friendly_name: "Subjective Exterior Temperature"
        value_template: |
          {% set temperature = states("sensor.dark_sky_apparent_temperature") | float %}
          {% if temperature > 65 -%}
          hot
          {%- elif temperature < 50 -%}
          cold
          {%- else -%}
          ok
          {%- endif %}

automation:
#  - alias: "Apply southern comfort when subjective temperature changes"
#    trigger:
#      platform: state
#      entity_id: sensor.subjective_exterior_temperature
#    action:
#      - service: script.apply_southern_comfort
#        data_template:
#          from: '{{ trigger.from_state}}'
#          to:  '{{ trigger.to_state }}'
#        
#  - alias: "Ensure southern comfort applied periodically"
#    trigger:
#      platform: time
#      minutes: '/15'
#      seconds: 00
#    action:
#      - service: script.apply_southern_comfort

script:
  # use the regular schedule when it's okay out. this is 68-72 on auto, with fan on auto
  climate_its_ok_outside:
    sequence:
      - service: climate.set_fan_mode
        entity_id: climate.home
        data:
          fan_mode: 'auto'
      - service: climate.set_temperature
        entity_id: climate.home
        data:
          operation_mode: 'auto'
          target_temp_low: !secret southern_comfort_low
          target_temp_high: !secret southern_comfort_high

  # when it's hot outside, set upper temperature to 70 and set fan to 'on'
  climate_its_hot_outside:
    sequence:
      - service: climate.set_fan_mode
        entity_id: climate.home
        data:
          fan_mode: 'on'
      - service: climate.set_temperature
        entity_id: climate.home
        data:
          operation_mode: 'cool'
          target_temp_low: !secret southern_comfort_low
          target_temp_high: !secret southern_comfort_ideal

  # when it's cold outside, set lower temperature to 70 and set fan to 'auto'
  climate_its_cold_outside:
    sequence:
      - service: climate.set_fan_mode
        entity_id: climate.home
        data:
          fan_mode: auto
      - service: climate.set_temperature
        entity_id: climate.home
        data:
          operation_mode: 'heat'
          target_temp_low: !secret southern_comfort_ideal
          target_temp_high: !secret southern_comfort_high

  # uses subject_exterior_temperature to call one of the climate
  apply_southern_comfort:
    sequence:
      - service: script.turn_on
        data_template:
          entity_id: script.climate_its_{{ states.sensor.subjective_exterior_temperature.state }}_outside
      # only announce if there was a 'from' passed in, which happens for the sensor state trigger automation
      - condition: template
        value_template: "{{ from }}"
      - service: notify.slack
        data_template:
          message: "I do declare, it's {{states.sensor.subjective_exterior_temperature.state}} outside"

group:
  southern_comfort_scripts:
    name: Southern Comfort Scripts
    entities:
      - sensor.subjective_exterior_temperature
      - script.apply_southern_comfort
      - script.climate_its_ok_outside
      - script.climate_its_hot_outside
      - script.climate_its_cold_outside
  
