automation:
  - alias: Sunrise
    trigger:
      platform: sun
      event: sunrise
      offset: '+00:30:00'
    action:
      service: script.turn_on
      entity_id: script.sunrise

  - alias: Sunset
    trigger:
      platform: sun
      event: sunset
    action:
      service: script.turn_on
      entity_id: script.sunset

script:
  sunrise:
    sequence:
      - service: script.sunrise_exterior
      - service: notify.slack
        data_template:
          message: ":city_sunrise:"

  sunrise_exterior:
    sequence:
      - service: light.turn_off
        entity_id: light.exterior

  sunset_living_room:
    sequence:
      - condition: state
        entity_id: light.living_room
        state: 'on'
      - service: hue.hue_activate_scene
        data:
          group_name: Living room
          scene_name: Read

  sunset_exterior:
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: Exterior
          scene_name: Dimmed

  sunset_bedroom:
    sequence:
      # don't mess with lights if they've been turned on
      - condition: state
        entity_id: light.bedroom
        state: 'on'
      # dont' mess with lights if someone is in bed
      - condition: state
        entity_id: sensor.anyone_in_bed
        state: 'off'
      - service: hue.hue_activate_scene
        data:
          group_name: Bedroom
          scene_name: Dimmed

  sunset:
    sequence:
      - service: script.sunset_living_room
      - service: script.sunset_bedroom
      - service: script.sunset_exterior
      - service: notify.slack
        data_template:
          message: ":city_sunset:"
