automation:
  - alias: Exterior Sunrise
    trigger:
      platform: sun
      event: sunrise
      offset: '+00:30:00'
    action:
      - service: notify.slack
        data_template:
          message: ":city_sunrise:"
      - service: light.turn_off
        entity_id: light.exterior

  - alias: House Sunset
    trigger:
      platform: sun
      event: sunset
    action:
      - service: notify.slack
        data_template:
          message: ":city_sunset:"
      - service: hue.hue_activate_scene
        data:
          group_name: Exterior
          scene_name: Dimmed

  - alias: Bedroom Sunset
    trigger:
      platform: sun
      event: sunset
    condition:
      condition: state
      entity_id: group.bedroom_lights
      state: 'off'
    action:
      service: scene.turn_on
      data:
        entity_id: scene.living_room_sunset

  - alias: Living Room Sunset
    trigger:
      platform: sun
      event: sunset
    condition:
      condition: state
      entity_id: light.living_room
      state: 'off'
    action:
      service: scene.turn_on
      data:
        entity_id: scene.living_room_sunset

scene:
  - name: Living Room Sunset
    entities:
      light.josh_night_stand:
        state: on
        brightness: 117
        color_temp: 369

  - name: Sun Room Sunset
    entities:
      light.sun_room_lamp:
        state: on
        brightness: 54
        color_temp: 369
