binary_sensor:
  - platform: apcupsd
sensor:
  - platform: apcupsd
    resources:
      - bcharge
      - linev
      - loadpct
      - nominv
      - numxfers
      - status
      - timeleft
      - tonbatt
